#!/bin/sh
#
#This is an example script for OpenMPI
#
#These commands set up the PBS Environment for your job:
#job name

#PBS -16 p1

#2 processes (mapped onto two cores of the same node) for 5 minutes
#PBS -l nodes=16,walltime=00:05:00
#PBS -l nodes=16:ppn=1,cput=00:05:00
#PBS -q debug
#PBS -M rkrish11@ncsu.edu

#error handling
#PBS -m abe
#output file
#PBS -o latency_test.out


echo
echo PBS JOB id is $PBS_JOBID
echo PBS_NODEFILE is $PBS_NODEFILE
echo PBS_QUEUE is $PBS_QUEUE
NPROCS=`wc -l < $PBS_NODEFILE`

echo

hostname

echo
cat $PBS_NODEFILE
echo NPROCS: $NPROCS

echo
mpirun ./p1
